export const CONFIGURATOR_NORMAL_MODE = "CNM";
export const CONFIGURATOR_EDIT_ORDER_MODE = "CEOM";
export const CONFIGURATOR_EDIT_CART_MODE = "CECM";
export const CONFIGURATOR_EDIT_UPGRADE_MODE = "CEUM";
