import HyperStore from "../../../public/images/dealers/hypers.jpg";
import DealerBikeOne from "../../../public/images/dealers/nireeka-dealer.jpg";
import DealerBikeTwo from "../../../public/images/dealers/Ashland-Electric.jpg";
import DealerBikeThree from "../../../public/images/dealers/bike-dealers.jpg";
import FlagUSA from "../../../public/images/US.svg";
import FlagCA from "../../../public/images/CA.svg";

export const dealers = {
  name: "General Questions",
  card: [
    {
      image: HyperStore,
      alt_image: "Hyper",
      head: "Dealership/Service Center",
      head_two: "Hyper Rides",
      title_1: "2330 Sunset Blvd St, 140, Rocklin, CA 95765 ",
      phone: "Sales / Text: (916) 594-4999",
      href_phone: "tel:+1(916) 594-4999",
      id: "0",
      // email: "Website: ",
      // name_href_mail: "https://hyperrides.com",
      // href_mail: "mailto:https://hyperrides.com/",
      website: "Website: ",
      href_website: "https://hyperrides.com/",
      name_href_website: "https://hyperrides.com/",
      head_title: "Note: ",
      title: "3:30PM - 7PM / 7 Days",
      flag_img: FlagUSA,
      alt_img: "usa",
      title_img: "United States",
    },
    {
      image: DealerBikeThree,
      alt_image: "bike",
      head: "Dealership/Service Center",
      head_two: "Shift Electric Vehicles",
      title_1: "1151 South Service Rd W, Unit 8, Oakville, ON, L6L 6K4 ",
      phone: "Phone: +1(888)490-6804",
      href_phone: "tel:+1 (888) 490-6804",
      id: "1",
      website: "Website: ",
      href_website: "https://www.shiftmotors.com",
      name_href_website: "https://www.shiftmotors.com/",
      head_title: "Note: ",
      title: "Please call ahead of your visit to make an appointment.",
      flag_img: FlagCA,
      alt_img: "canada",
      title_img: "Canada",
      email: "",
      name_href_mail: "",
      href_mail: "",
    },
    // {
    //   image: DealerBikeOne,
    //   alt_image: "bike",
    //   head: "Service Center",
    //   head_two: "YouMove",
    //   title_1: "524 Rhode Island Ave NE, Washington, DC ",
    //   phone: "Phone: +1 (703) 898-6900",
    //   href_phone: "tel:+1(703)898-6900",
    //   id: "2",
    //   email: "Email: ",
    //   name_href_mail: "youmovesyndicate@gmail.com",
    //   href_mail: "mailto:youmovesyndicate@gmail.com",
    //   website: "Website: ",
    //   href_website: "https://www.youmove.us/book-online",
    //   name_href_website: "https://www.youmove.us",
    //   head_title: "Note: ",
    //   title: "Please call ahead of your visit to make an appointment.",
    //   flag_img: FlagUSA,
    //   alt_img: "usa",
    //   title_img: "United States",
    // },
    // {
    //   image: DealerBikeTwo,
    //   alt_image: "bike",
    //   head: "Dealership/Service Center",
    //   head_two: "Ashland Electric Bikes",
    //   title_1: "1678 Ashland St. Ashland, OR 97520 ",
    //   phone: "Phone: +1(541)951-3034",
    //   href_phone: "tel:+1 (541) 951-3034",
    //   id: "3",
    //   name_href_mail: "contact@ashlandelectricbikes.com",
    //   href_mail: "mailto:contact@ashlandelectricbikes.com",
    //   email: "Email: ",
    //   website: "Website: ",
    //   href_website: "https://ashlandelectricbikes.com/",
    //   name_href_website: "https://ashlandelectricbikes.com",
    //   head_title: "Hours: ",
    //   title: "Tuesday – Saturday 11:00 – 5:00",
    //   flag_img: FlagUSA,
    //   alt_img: "usa",
    //   title_img: "United States",
    // },
  ],
};
